apiVersion: apps/v1
kind: Deployment
metadata:
  name: campusly-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: campusly
  template:
    metadata:
      labels:
        app: campusly
    spec:
      containers:
        - name: campusly
          image: docker.io/library/campusly:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
